# Generated by Django 3.0.8 on 2020-08-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categori',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categori_num',
            new_name='category_num',
        ),
    ]
