# Generated by Django 3.1 on 2020-08-09 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200803_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='소속 카테고리 번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정시간'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='댓글작성시간'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='소속 게시글 번호'),
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post')),
            ],
        ),
    ]
