# Generated by Django 3.1 on 2020-08-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200811_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_num',
        ),
    ]
