# Generated by Django 3.1 on 2020-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_category_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attach',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='newCategory', max_length=50, verbose_name='카테고리 제목'),
        ),
    ]
