# Generated by Django 3.1 on 2020-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200811_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach',
            field=models.ImageField(default='', upload_to='../static/image', verbose_name='첨부파일'),
        ),
    ]
