# Generated by Django 3.1 on 2020-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attach',
            field=models.ImageField(default='', upload_to='h0zzae/h0zzae/static/image', verbose_name='첨부파일'),
        ),
    ]
