# Generated by Django 3.1 on 2020-08-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200813_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='password',
            field=models.CharField(default='0000', max_length=4, verbose_name='댓글 비밀번호'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Replys', to='home.post', verbose_name='소속 게시글 번호'),
        ),
    ]
