# Generated by Django 3.1 on 2020-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200823_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_num',
            field=models.IntegerField(default=0, verbose_name='소속 카테고리 번호'),
        ),
    ]
