# Generated by Django 3.1 on 2020-08-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200824_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='소속 카테고리 번호'),
        ),
    ]
