# Generated by Django 3.1 on 2020-09-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200827_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='home.category', verbose_name='소속 카테고리 번호'),
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
