# Generated by Django 3.1 on 2020-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200902_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='H0zzaeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('profileText', models.CharField(max_length=200, verbose_name='자기소개')),
                ('githubUrl', models.URLField(verbose_name='깃허브사이트')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='static/image/', verbose_name='프로필사진')),
            ],
        ),
    ]
