# Generated by Django 3.1 on 2020-09-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_h0zzaedate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='H0zzaeDate',
            new_name='H0zzaeData',
        ),
    ]
