# Generated by Django 3.1 on 2020-09-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200902_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='H0zzaeData',
            new_name='H0zzae_Data',
        ),
    ]
