# Generated by Django 3.1 on 2020-09-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200902_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='h0zzae_data',
            name='AdminPassword',
            field=models.CharField(default='12345qwert', max_length=20, verbose_name='관리자권한번호'),
        ),
    ]
