# Generated by Django 3.1 on 2020-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_h0zzae_data_adminpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h0zzae_data',
            name='AdminPassword',
            field=models.CharField(max_length=20, verbose_name='관리자권한번호'),
        ),
    ]
